# This file was generated by GoReleaser. DO NOT EDIT.
cask "gasa" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "f279168d2381f7aeb7bc2b049b99728883d553cbdef237c0372c74c56ed7ca1d"
      url "https://github.com/BretFisher/gasa/releases/download/v#{version}/gasa_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "935f5cae24b0dd79409830a8edd3da1692d455c6eb18601400defd8f43653ab2"
      url "https://github.com/BretFisher/gasa/releases/download/v#{version}/gasa_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8cee70644a4f1dd616d82366707b4e73381bc2824b2554d8fda698b6adc9aeb8"
      url "https://github.com/BretFisher/gasa/releases/download/v#{version}/gasa_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cd9846a7eff300ed4a6ed9b154f52bb22ff1982197f6048137bedab562a4472b"
      url "https://github.com/BretFisher/gasa/releases/download/v#{version}/gasa_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gasa"
  desc "GitHub Actions Security Assessment"
  homepage "https://github.com/bretfisher/gasa"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gasa"

  # No zap stanza required

end
