# This file was generated by GoReleaser. DO NOT EDIT.
cask "gasa" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "3b5d79403acaf84faa4fcbd4b50a0b2a4e08dceb38f5f70e8c6ee9ec18154c95"
      url "https://github.com/BretFisher/gasa/releases/download/v#{version}/gasa_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d84cf1adef311a6dd1c72154a44f6a9e0ccf58443159529facf28b73c1ccc577"
      url "https://github.com/BretFisher/gasa/releases/download/v#{version}/gasa_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bb3dc375056d6a1ab3a4bfc11445e031ba8f96b41dbfdf8facee0503c82914e7"
      url "https://github.com/BretFisher/gasa/releases/download/v#{version}/gasa_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "797e8aa902cfdc7e02ebe863c9b2fe217d6bcb63377ab56a6405611e6482c706"
      url "https://github.com/BretFisher/gasa/releases/download/v#{version}/gasa_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gasa"
  desc "GitHub Actions Security Assessment"
  homepage "https://github.com/bretfisher/gasa"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gasa"

  # No zap stanza required

end
