# This file was generated by GoReleaser. DO NOT EDIT.
cask "gasa" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "2a09e615699723f04415cd513337a3de5c2f6eaebf5d94416dda9de830c33e08"
      url "https://github.com/BretFisher/gasa/releases/download/v#{version}/gasa_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1b1cafc7f14153ad17a5f42d1c94e2f5018921b221f44fdfc25ccee3ccd4b1e8"
      url "https://github.com/BretFisher/gasa/releases/download/v#{version}/gasa_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6cf372be3ab0d5e979dfcab2f2b15fb37adb973761580cd88bde37bfec88c8b6"
      url "https://github.com/BretFisher/gasa/releases/download/v#{version}/gasa_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "65914c7ee7eda30d76abb66d551aa8e793d5378fcd65ffcc6038c7a1cbe737c7"
      url "https://github.com/BretFisher/gasa/releases/download/v#{version}/gasa_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gasa"
  desc "GitHub Actions Security Assessment"
  homepage "https://github.com/bretfisher/gasa"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gasa"

  # No zap stanza required

end
